### ISSUE TITLE
PCB: Choose appropriate IO for HiL pins with less constraints (GPIO)

### ISSUE THREAD

**Issue by HolgerStenberg** [IL2232-HT2022-HIL/HARDWARE_DEV#10]
In order to get a optimal routing for the adapter board, "repining"  of the HiL board shall be conducted in a way that don't require signals to travel far on the board. When a repinning that is considered good enought, this task is completed.

**Comment by HolgerStenberg** [comment]
@matthiasthomasbecker are there any requirements on the pins for the following components in your shield that we need to emulate? 
74HC595D - shift register
OLED Display

If the answer is no I will try to route the adapter board with these pins as generic GPIO pins. 

/Holger

**Comment by matthiasthomasbecker** [comment]
Hi Holger,

they have pre-defined pins. They are shown in the schematics (OLED on page 1 and the shift register on page 3). Let me know if you want to discuss earlier than the next meeting.

Best,
Matthias

**Comment by matthiasthomasbecker** [comment]
ah now I understand :)
in both cases there can be SPI involved. For the shift register its more simple than for the display. 
I have them on two different SPI interfaces. 
There should be the possibility to use them with SPI as well (not necessarily included in the project but the adapter should allow it).
This is the configuration for the Nucleo_L476RG with the shield attached. 
<img width="1120" alt="Screenshot 2022-10-03 at 16 08 40" src="https://user-images.githubusercontent.com/64021163/193598430-9a088c26-0d1e-414a-9b43-172dd035ab40.png">

**Comment by HolgerStenberg** [comment]
Allright! I will try configuring them with SPI. I will reach out If there are any problems! 

/Holger

**Comment by HolgerStenberg** [comment]
Hello again @matthiasthomasbecker! 

Could you just verify that I'm thinking correctly regarding the shift register pinning: 

595-SHCP: Should be connected to a SPI SCK  pin
595-STCP: Can be connected to any available pin
595-DS: Should be connected to a SPI MOSI pin
595-Enable: You connected a timer to this pin, but I guess it can be connected to a generic pin? 
595-Reset: Can be connected to any available pin

**Comment by matthiasthomasbecker** [comment]
Hi,
I also had a look and agree with almost all of the mapping. 

For the 595-Enable pin, it would be great if it could connect to a timer pin (of an otherwise unused timer) on the HIL-Board as well. 
That we have the possibility to measure the PWM signal (if it is used by the system under test) to see which brightness level the LEDs are at a specific time (I would say out of scope of the project work, or nice to have).

**Comment by HolgerStenberg** [comment]
Hello @matthiasthomasbecker. Here is a Friday sneak-peak of the finalised schematics. I perform some extra verification steps in order to call the circuit complete! Soon this is done! :) 

[ADAPTER_BOARD_SCHEMATICS_1.0.pdf](https://github.com/IL2232-HT2022-HIL/HARDWARE_DEV/files/9786981/ADAPTER_BOARD_SCHEMATICS_1.0.pdf)
