### ISSUE TITLE
Send the adapter board for production

### ISSUE THREAD

**Issue by HolgerStenberg** [IL2232-HT2022-HIL/HARDWARE_DEV#16]
Once the board has been reviewed by matthias, it can be ordered from JLC PCB. The required files for ordering can be found under "/ADAPTER_BOARD/GERBERS/V1". Only request from project group is that the PCB will be black, should not affect cost.

**Comment by HolgerStenberg** [comment]
Give me one second to fix an issue regarding the ordering. We need to verify that certain functions work on the HiL board first (may be conflicts)

**Comment by HolgerStenberg** [comment]
@matthiasthomasbecker Is this completed?

**Comment by matthiasthomasbecker** [comment]
Hi Holger,

No this is not completed.
I am still waiting for the updated BOM files to work with JLCPCB.

The current version does not work with their page.

Could you please send me an updated version by email once done?

Best,
Matthias

From: Holger Stenberg ***@***.***>
Reply to: IL2232-HT2022-HIL/HARDWARE_DEV ***@***.***>
Date: Friday, 11 November 2022 at 11:52
To: IL2232-HT2022-HIL/HARDWARE_DEV ***@***.***>
Cc: Matthias Becker ***@***.***>, Mention ***@***.***>
Subject: Re: [IL2232-HT2022-HIL/HARDWARE_DEV] Send the adapter board for production (Issue #16)


@matthiasthomasbecker<https://github.com/matthiasthomasbecker> Is this completed?

**Comment by HolgerStenberg** [comment]
Certainly! I will try to get it done today. 👍
