### ISSUE TITLE
Aquire and familiarize with hardware boards

### ISSUE THREAD

**Issue by HolgerStenberg** [IL2232-HT2022-HIL/HARDWARE_DEV#3]
Find out about, install development environment.

**Comment by HolgerStenberg** [comment]
There are two boards that will be part of the project:
- The MCU Development Board: Nucleo-L476RG
- The MCU HiL Board : Nucleo-F767ZI 

I will investigate if these boards can be found as CAD-files

**Comment by HolgerStenberg** [comment]
Additional information from mattias regarding what signals that are of interest is required to continue

**Comment by HolgerStenberg** [comment]
MII or RMII ehternet interface? 
- [ ] Solved?

**Comment by sofiecmf** [comment]
We need for sure that these peripherals exists and do not collide with anything else :

1 USART bus
1 I2C bus
1 SPI bus
Ethernet (RMII or MII)
DAC for HiL (for potentiometer emulator)
ADC for Development MCU (for potentiometer read)

**Comment by HolgerStenberg** [comment]
We are thinking of combining the power from both pcbs with only one usb cable (for ease-of-use).
Currently looking into how to configure the boards such that the MCU Development Board can power the adapter board and the HiL Board

**Comment by HolgerStenberg** [comment]
On small board: 
dis-connect JP1 for 300 mA over ST-link
